### PR TITLE
DS-2648

### PR DESCRIPTION
**Pull request by jrwishart**
Pull request before flipTextAnalysis (depends on the EntityExtractionWidget here).

Along with the unit tests in tests/test-entityextractionwidget.R there is a test page here 
https://test.displayr.com/Dashboard?project_id=-676287

### CODE REVIEW

**Comment by JustinCCYap** [comment]
With the sorting of the entities and variants, can we break ties alphabetically?

**Comment by jrwishart** [comment]
> 
> 
> With the sorting of the entities and variants, can we break ties alphabetically?

Good suggestion and now done. Commit cb44969 should fix this.

**Comment by JustinCCYap** [comment]
Does the browser() call need to be there or should it be removed?

**Comment by jrwishart** [comment]
> Does the browser() call need to be there or should it be removed?

It definitely shouldn't be there. Sorry about that. Wish R/Rstudio would notice these when running tests and checks. It gets ignored when running tests and R CMD checks. I'll remove the browser call and do a double check of all the output again and re-commit

**Pull request merged**
