### PR TITLE
DS-5301: Fix dataset merging by case widget if mergesrc var. is not last

### PR DESCRIPTION
**Pull request by mwm-displayr**
* When the second dataset contains a variable not in the first, the "mergesrc" variable no longer appears last in the data.

### CODE REVIEW

**Review by JustinCCYap — APPROVED** [review]
LGTM, welcome back Math!

**Comment by mwm-displayr** [comment]
Thanks, @JustinCCYap! Are you aware of anywhere else in the flipData or flipFormat code that make a similar assumption about the "mergesrc" variable being the last one in the merged data set?

**Comment by JustinCCYap** [comment]
I couldn't find anywhere else that makes that assumption. It is implicitly becomes the last (most of the time) due to:
https://github.com/Displayr/flipData/blob/master/R/mergedatasetsbycase.R#L1944

**Comment by mwm-displayr** [comment]
Thanks @JustinCCYap. What is the rationale behind that check? Doesn't `mergeSrc` always need to be updated regardless if every input dataset already has a `mergeSrc` already?

**Comment by JustinCCYap** [comment]
Hmm you might be correct. @chrisfacer?

**Comment by JustinCCYap** [comment]
I think when all data sets have `mergeSrc`, and `when.multiple.labels.for.one.value = "Create new values for the labels"` (by default), the merging code will merge them correctly so there is no need to do anything extra here by default. But if the setting is `"Use label from preferred data set"` then we could run into an issue. Maybe this is worth filing as a bug into Jira.

**Comment by JustinCCYap** [comment]
We might have to treat merging of `mergeSrc` differently, i.e. always `"Create new values for the labels"`.

**Comment by mwm-displayr** [comment]
Thought I could add a simple unit test for this as follows, but `mergesrc` is the last variable in the merged output below. I'm missing what is different about the data in the bug report.
```
df1 <- data.frame(x=1:2)
df2 <- data.frame(x=2:3, z=c('a', 'b'))
file1 <- tempfile(fileext = ".sav")
file2 <- tempfile(fileext = ".sav")
outfile <- "foo.sav"  # MergeDataSetsByCase complains if special chars. in filename
haven::write_sav(df1, file1)
haven::write_sav(df2, file2)
result <- MergeDataSetsByCase(c(file1, file2), outfile)
out <- haven::read_spss(outfile)
colnames(out)[3] == "z"
```

**Comment by JustinCCYap** [comment]
I'm not sure why it isn't last too. I thought it wasn't the last variable because it appeared in the input data files, but that doesn't seem to be the case? You might have to debug this locally.

**Comment by mwm-displayr** [comment]
Thanks, should be sorted in f869495f2. `df1` in my example above should have a `mergesrc` variable, e.g. `df1 <- data.frame(x=1:2, mergesrc = as.factor(c('a', 'b'))`.

**Comment by mwm-displayr** [comment]
Following up on the behaviour when both datasets contain a `mergesrc`, the output `mergesrc` appears correct for a toy example I tried and actually errors if you comment out the `if` statement on L1944.

**Pull request merged**
